FROM python:3.7-slim

RUN set -x \
    && apt-get update \
    && apt-get install -y git \
    && apt-get clean

ENV PIP_CACHE_DIR /tmp/pipcache
ENV PIPENV_CACHE_DIR /tmp/pipenvcache
RUN pip install pipenv

RUN mkdir /app
WORKDIR /app

COPY Pipfile Pipfile.lock setup.py ./
COPY sampleapp ./sampleapp
COPY bin ./bin
RUN pipenv install --dev --deploy
